language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"

matrix:
  allow_failures:
    - python: "pypy"

install:
  - pushd .
  # installing mongodb
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - make setup

script:
    # finally run tests
    - make ci_test

after_success:
  - coveralls
